spring:
  sql.init.mode: always
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  # The SQL dialect makes Hibernate generate better SQL for the chosen database
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  #JPA settings
  jpa.hibernate.ddl-auto: create-drop

